### ISSUE TITLE
Service Executable Path

### ISSUE THREAD

**Issue by ccjjmartin** [chestm007/linux_thermaltake_riing#10]
**Describe the bug**
The executable path in my service file was to a location that didn't exist.

**To Reproduce**
1. Follow the install instructions on Linux Mint using pip
2. Notice using `which linux-thermaltake-rgb` that the file path is `/usr/local/bin/linux-thermaltake-rgb` instead of the defined `/usr/bin/linux-thermaltake-rgb`

**Expected behavior**
The service should be able to start without failures.

**Stacktraces / logs**
Error status:
```
ccjjmartin@aquaman:~$ systemctl --user status linux-thermaltake-rgb.service
● linux-thermaltake-rgb.service
   Loaded: loaded (/usr/lib/systemd/user/linux-thermaltake-rgb.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-01-15 02:10:07 CST; 46s ago
  Process: 2398 ExecStart=/usr/bin/linux-thermaltake-rgb (code=exited, status=203/EXEC)
 Main PID: 2398 (code=exited, status=203/EXEC)

Jan 15 02:10:07 aquaman systemd[2012]: linux-thermaltake-rgb.service: Service hold-off time over, scheduling restart.
Jan 15 02:10:07 aquaman systemd[2012]: linux-thermaltake-rgb.service: Scheduled restart job, restart counter is at 5.
Jan 15 02:10:07 aquaman systemd[2012]: Stopped linux-thermaltake-rgb.service.
Jan 15 02:10:07 aquaman systemd[2012]: linux-thermaltake-rgb.service: Start request repeated too quickly.
Jan 15 02:10:07 aquaman systemd[2012]: linux-thermaltake-rgb.service: Failed with result 'exit-code'.
Jan 15 02:10:07 aquaman systemd[2012]: Failed to start linux-thermaltake-rgb.service.
```

**Desktop (please complete the following information):**
 - Linux Mint 19.1 Tessa

**Solution**
Updating the ExecStart line to include the `local` directory fixed the issue for me:
```
ExecStart=/usr/local/bin/linux-thermaltake-rgb
```

**Thanks**
I am up and running and able to change my fan colors now.  Thanks for your hard work on this project!

**Comment by chestm007** [comment]
fixed in e54e2f5a54a551a15234e00dc490b2c283dc306d pending release
