### ISSUE TITLE
G3 controller device ID

### ISSUE THREAD

**Issue by duncanthrax** [chestm007/linux_thermaltake_riing#12]
Hi, thanks for this, it works for me.

However, I have a controller here that has device ID 0x2135 instead of 0x1fa5. Changing that value in the udev rule as well as the driver makes it work OK.

`hid-generic 0003:264A:2135.000A: hiddev1,hidraw4: USB HID v1.11 Device [ ... ] on usb-0000:00:14.0-10.1/input0`

The controller is from a fan 3-pack called "Riing Trio 12 RGB TT Premium Edition".

**Comment by chestm007** [comment]
Hi, awesome news, I'm glad you found it useful.

I've implemented what i believe should make this software work out of the box for you in the latest master (commit 53888f0c408c3c70da17befa06afa06bab67537f for reference)

Let me know if you have issues, cheers
