### ISSUE TITLE
error: no matching distribution found 

### ISSUE THREAD

**Issue by dotanuki** [chestm007/linux_thermaltake_riing#2]
Collecting linux-thermaltake-rgb
  Downloading https://files.pythonhosted.org/packages/55/e5/949b433207f5bd128d9b9d7c33861973669d4154f237a86a57ee34b63435/linux_thermaltake_rgb-0.0.2.tar.gz
Collecting gobject (from linux-thermaltake-rgb)
  Could not find a version that satisfies the requirement gobject (from linux-thermaltake-rgb) (from versions: )
No matching distribution found for gobject (from linux-thermaltake-rgb)

I am running linux mint 19 
kernal version:
Linux ryzeng 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chestm007** [comment]
It looks like i have listed the wrong package in setup.py, I'll have a closer look tomorrow as im currently away from my dev machine

**Comment by egloffmark** [comment]
I have the same issue will be nice if you can fix this problem. Thank you. I am also happy to provide you a donation if you support me to get it running

**Comment by chestm007** [comment]
@egloffmark @dotanuki are you using python3's pip to install this?

**Comment by dotanuki** [comment]
no the system is using Python 2.7.15rc1
