### ISSUE TITLE
Manjaro Install Issue

### ISSUE THREAD

**Issue by JCP281** [chestm007/linux_thermaltake_riing#30]
**Describe the bug**
Upon trying to install the package off AUR (running Manjaro) I get a failed to commit transaction error saying that there are conflicting files:

conflicting files:
python-yaml: /usr/lib/python3.7/site-packages/PyYAML-5.1.1-py3.7.egg-info already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__init__.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/constructor.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/cyaml.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/dumper.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/emitter.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/error.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/events.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/loader.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/nodes.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/parser.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/reader.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/representer.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/resolver.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/scanner.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/serializer.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/__pycache__/tokens.cpython-37.pyc already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/composer.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/constructor.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/cyaml.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/dumper.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/emitter.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/error.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/events.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/loader.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/nodes.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/parser.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/reader.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/representer.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/resolver.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/scanner.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/serializer.py already exists in filesystem
python-yaml: /usr/lib/python3.7/site-packages/yaml/tokens.py already exists in filesystem

I am stuck here. I am running Manjaro version 18.0.4 with Gnome. Other than that, stock install. I am new to linux so this might be an easy one to solve. 

PIP is installed as well as Python 3.7.

**Comment by chestm007** [comment]
it looks like you have yaml (possibly pyyaml) installed directly via pip.
`sudo pip uninstall pyyaml` and then rerunning the install of this package by whatever aur helper you use should fix it. :)

**Comment by JCP281** [comment]
Worked beautifully. Thanks for the help!

**Comment by chestm007** [comment]
Awesome! :)
