### ISSUE TITLE
Pure plus 12 support Ubuntu 18.04 ? 

### ISSUE THREAD

**Issue by teleporsche** [chestm007/linux_thermaltake_riing#4]

**Comment by chestm007** [comment]
https://www.thermaltake.com.au/Cooler/Case_Fan_/Pure/C_00003232/Pure_Plus_12_RGB_Radiator_Fan_TT_Premium_Edition_3_Fan_Pack_/design.htm

if its in relation to this product, i feel like this should work, please let me know if it doesnt

**Comment by congabanana** [comment]
> https://www.thermaltake.com.au/Cooler/Case_Fan_/Pure/C_00003232/Pure_Plus_12_RGB_Radiator_Fan_TT_Premium_Edition_3_Fan_Pack_/design.htm
> 
> if its in relation to this product, i feel like this should work, please let me know if it doesnt

Hi, thanks for you creating this. I can confirm these work by setting them up as:

````
controllers:
  - unit: 1
    type: g3
    devices:
      1: Riing Plus
      2: Riing Plus
      3: Riing Plus
````
(I have 3 fans)
