### ISSUE TITLE
Readme Instructions

### ISSUE THREAD

**Issue by ccjjmartin** [chestm007/linux_thermaltake_riing#9]
**Describe the bug**
Missing dependencies on fresh Linux (Mint and Ubuntu) install.

**To Reproduce**
1. On a fresh install follow the instructions in the readme and notice this error:
```
Failed building wheel for dbus-python
```

**Expected behavior**
A successful message should appear:
```
Successfully installed cycler-0.10.0 kiwisolver-1.0.1 linux-thermaltake-rgb-0.0.12.post1544541597 matplotlib-3.0.2 numpy-1.16.0 pyparsing-2.3.1 python-dateutil-2.7.5 pyusb-1.0.2 scipy-1.2.0
```

**Desktop (please complete the following information):**
 - Linux Mint 19.1 Tessa

**Solution**
The readme should include a reference to the required python dev package, installed with:
```
sudo apt-get install python3-dev
```

**Comment by ccjjmartin** [comment]
Got the answer from here: https://github.com/giampaolo/psutil/issues/1143#issuecomment-334694641

**Comment by chestm007** [comment]
@ccjjmartin  Is `python3-dev` still required for the latest version of this project.

**Comment by ccjjmartin** [comment]
@chestm007 My errors were occurring during the install of the `dbus-python` package before any of the other setup from this project, seeing as that is still a dependency of this project I would say yes it will still be required: https://github.com/chestm007/linux_thermaltake_riing/blob/beb828d2f4c6632dd41f77fec8a0d1812e6a622b/setup.py#L25

I didn't run through the whole setup process again though and I should have posted the full logs here rather than the one liner above so you could verify, my bad.

**Comment by chestm007** [comment]
That dependency has been removed since your last comment - it was lingering crud from a poorly conceived idea i had prior to making this code public.

Closing as this should be solved now
